[package]
name = "xch-slot-machine"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["yakuhito <y@kuhi.to>"]
homepage = "https://github.com/Yakuhito/slot-machine"
repository = "https://github.com/Yakuhito/slot-machine"

[dependencies]
clvmr = "0.8.0"
chia = "0.13.0"
hex-literal = "0.4.1"
clvm-traits = "0.13.0"
once_cell = "1.19.0"
num-bigint = "0.4.6"
bip39 = "2.0.0"
getrandom = "0.2.15"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
hex = "0.4.3"

chia-wallet-sdk = { git = "https://github.com/Rigidity/chia-wallet-sdk.git", rev = "da42dcb8b5cfea13490861af7b505ac38af67311"}

[dev-dependencies]
anyhow = "1.0.86"
rstest = "0.22.0"

[target.aarch64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10.64", features = ["vendored"] }
openssl-sys = { version = "0.9.102", features = ["vendored"] }

[target.aarch64-unknown-linux-musl.dependencies]
openssl = { version = "0.10.64", features = ["vendored"] }
openssl-sys = { version = "0.9.102", features = ["vendored"] }

[target.x86_64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10.64", features = ["vendored"] }
openssl-sys = { version = "0.9.102", features = ["vendored"] }

[target.x86_64-unknown-linux-musl.dependencies]
openssl = { version = "0.10.64", features = ["vendored"] }
openssl-sys = { version = "0.9.102", features = ["vendored"] }